### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nesquik011** [MAVIS-SLAM/ORB_SLAM3_MULTI#4]
did you fix orb slam3 memory leaks ? 
do you have discord ?
why not make channel for orb slam 3 and slam system so we can all communicate together , if you dont have one 
and may you make build easy for windows ?

**Comment by 1fwang** [comment]
> did you fix orb slam3 memory leaks ? do you have discord ? why not make channel for orb slam 3 and slam system so we can all communicate together , if you dont have one and may you make build easy for windows ?

Hi nesquik011,

Thanks for you message.

Due to time constraints, I did not specifically fix the memory leakages while re-implmenting ORB-SLAM3 with OpenMAVIS. However, I welcome anyone willing to contribute to this repo to improve this framework. Additionally, I have not created a channel for communication, but you can contact me via email at: 1fwang927@gmail.com. Finally, I usually only work on Linux and do not have a Windows system desktop / laptop, so I am currently unable to help with testing and compiling on Windows. Sorry for the inconvenience may brought to you.

BR,
Yifu

**Comment by Melvin-leo** [comment]
I am experiencing killed process at this line in system.cc

        bool bVocLoad = mpVocabulary->loadFromTextFile(strVocFile);
I am not sure if this is a part of the memory leak. May I know if anyone experiences it?

**Comment by 1fwang** [comment]
> I am experiencing killed process at this line in system.cc
> 
> ```
>     bool bVocLoad = mpVocabulary->loadFromTextFile(strVocFile);
> ```
> 
> I am not sure if this is a part of the memory leak. May I know if anyone experiences it?

Hi, have you unzip the ORBvoc.txt.tar.gz before running the program?

**Comment by Melvin-leo** [comment]
Sorry, I made a mistake on the file path, I just realised it while troubleshooting. Sorry about that.
